serve_metric_enabled = true
serve_metric_addr = "0.0.0.0:3000"
ws_addr = "0.0.0.0:8080"
clutch_node_ws_url = "ws://127.0.0.1:8081"
log_level = "info"
seq_url = "http://127.0.0.1:5341"
seq_api_key = "FZii3D6ILDI38a0oIeDL"
jwt_secret = "iP8BoK3dJfTQGz5UyXq9NwL7e0vCmAhR6S2YxE1ZpDt4"
jwt_expiration_hours = 6